strategy:
  adx_threshold: 22
  current_capital: 10000
  max_position_size: 0.2
  max_trades_per_day: 15
  min_hours_between_trades: 1
  min_position_size: 0.01
  profit_target: 0.05171871937655084
  require_trend_alignment: false
  require_volume_confirmation: false
  risk_factor: 0.02
  risk_fraction: 0.02
  rsi_overbought: 65
  rsi_oversold: 35
  stop_loss: 0.04608258890530529
