# Momentum Strategy Configuration
strategy:
  # Required parameters
  risk_fraction: 0.02
  max_position_size: 0.2
  min_position_size: 0.01
  stop_loss: 0.05
  profit_target: 0.1
  
  # Strategy-specific parameters
  rsi_oversold: 30
  rsi_overbought: 70
  adx_threshold: 25
  risk_factor: 0.02
  capital: 10000
  
  # Momentum indicators
  rsi_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Risk parameters
  max_daily_loss: 0.05
  max_correlation: 0.7
  var_limit: -0.1