strategy:
  adx_threshold: 25
  capital: 10000
  macd_fast: 12
  macd_signal: 9
  macd_slow: 26
  max_position_size: 0.2
  min_position_size: 0.01
  profit_target: 0.1
  risk_factor: 0.02
  risk_fraction: 0.02
  rsi_overbought: 70
  rsi_oversold: 30
  rsi_period: 14
  stop_loss: 0.05
