environment: sandbox

database:
  type: postgresql
  host: localhost
  port: 5432
  name: trading_db
  user: trading_user
  password: scottbrough

exchange:
  name: kraken
  sandbox: true
  api_url: https://demo-futures.kraken.com/derivatives
  websocket_url: wss://demo-futures.kraken.com/ws/v1
  api_key: 7RIQ3BKfVNxZI7tiVFJpQugOWQeXwBCxQ1iN233eS+4NaKnMa02mpnMl
  api_secret: D1CCIpSmnSBIeDixfNlwKAw2i55sWhsJHsKnV6fkVr7mVnn+8k+IE2r5ad7bGli07S9yTwQoJWcFYVcuBc3ZROqY
  rate_limit: 0.2  # requests per second

data:
  symbols:
    - BTC/USD
    - ETH/USD
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  cache_size: 1000
  update_interval: 1

strategy:
  default_strategy: enhanced
  risk:
    max_drawdown: 0.15
    max_position_size: 0.2
    min_position_size: 0.01
    max_risk_per_trade: 0.02
    max_daily_loss: 0.05
    max_correlation: 0.7
    var_limit: -0.1
    account_balance: ${ACCOUNT_BALANCE}
  parameters:
    rsi_period: 14
    ma_period: 20
    volatility_period: 20
    profit_target: 0.02
    stop_loss: 0.01

monitoring:
  dashboard_port: 8050
  update_interval: 5
  metrics:
    - pnl
    - win_rate
    - sharpe_ratio
    - max_drawdown
    - volatility
  alerts:
    slack_webhook: ${SLACK_WEBHOOK}
    email: ${ALERT_EMAIL}

# Added paper trading parameters
trading_params:
  initial_balance: 10000
  daily_trade_limit: 20
  min_profit_threshold: 0.003
  max_open_positions: 5
  compound_frequency: 24
  monthly_injection: 0.0
  transaction_fee_rate: 0.0026  # Kraken taker fee (0.26%)
  slippage_factor: 0.001        # Additional slippage (0.1%) for market orders
  stop_loss: 0.05               # 5% stop loss
  profit_target: 0.1            # 10% take profit