# Trend Following Strategy Configuration
strategy:
  # Required parameters
  risk_fraction: 0.02
  max_position_size: 0.2
  min_position_size: 0.01
  stop_loss: 0.05
  profit_target: 0.1
  amount: 1.0  # Default amount for position sizing
  
  # Strategy-specific parameters
  trend_threshold: 0.3
  quality_threshold: 0.6
  adx_threshold: 25
  risk_factor: 0.02
  capital: 10000
  
  # Trend indicators
  ema_fast: 9
  ema_medium: 21
  ema_slow: 50
  atr_period: 14
  
  # Risk parameters
  max_daily_loss: 0.05
  max_correlation: 0.7
  var_limit: -0.1